AWSTemplateFormatVersion: '2010-09-09'
Description: ACM certificate for Attractor Factory ingress domain

Parameters:
  DomainName:
    Type: String
    Default: factory.pelx.ai
  HostedZoneId:
    Type: String
    Description: Route53 hosted zone id for the parent domain

Resources:
  IngressCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CertificateArn:
    Value: !Ref IngressCertificate
    Export:
      Name: !Sub '${AWS::StackName}-CertificateArn'
