AWSTemplateFormatVersion: '2010-09-09'
Description: Attractor Factory ECR repositories

Parameters:
  StackPrefix:
    Type: String
    Default: attractor-factory
  RetainImageCount:
    Type: Number
    Default: 60
    MinValue: 1

Resources:
  ApiRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${StackPrefix}/factory-api'
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last ${RetainImageCount} images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": ${RetainImageCount}
                },
                "action": { "type": "expire" }
              }
            ]
          }

  WebRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${StackPrefix}/factory-web'
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last ${RetainImageCount} images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": ${RetainImageCount}
                },
                "action": { "type": "expire" }
              }
            ]
          }

  ControllerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${StackPrefix}/factory-runner-controller'
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last ${RetainImageCount} images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": ${RetainImageCount}
                },
                "action": { "type": "expire" }
              }
            ]
          }

  RunnerRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${StackPrefix}/factory-runner'
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last ${RetainImageCount} images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": ${RetainImageCount}
                },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  ApiRepositoryUri:
    Value: !GetAtt ApiRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-ApiRepositoryUri'
  WebRepositoryUri:
    Value: !GetAtt WebRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-WebRepositoryUri'
  ControllerRepositoryUri:
    Value: !GetAtt ControllerRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-ControllerRepositoryUri'
  RunnerRepositoryUri:
    Value: !GetAtt RunnerRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-RunnerRepositoryUri'
